# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Azkar' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Azkar
pod 'IQKeyboardManager'

  target 'AzkarTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'AzkarUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
