# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Azkar' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  
  # Pods for Azkar
  pod 'IQKeyboardManager'
  pod 'Adhan'
  pod 'WWCalendarTimeSelector'
  pod 'PDFReader'
  pod 'Firebase/Messaging' , '~> 4.3.0'
  pod 'Firebase/Analytics' , '~> 4.3.0'
  pod 'GoogleAnalytics'

  
  target 'AzkarTests' do
    inherit! :search_paths
    # Pods for testing
  end
  
  target 'AzkarUITests' do
    inherit! :search_paths
    # Pods for testing
  end
  
end
